// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyecto_sena.Data;

#nullable disable

namespace proyecto_sena.Migrations
{
    [DbContext(typeof(DBcontext))]
    partial class DBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proyecto_sena.Models.usuario1", b =>
                {
                    b.Property<int>("usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("usuario_Id"));

                    b.Property<string>("usuario_Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario_Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario_Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario_correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("usuario_Id");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
